# vim: set ft=dockerfile :
FROM rust:1.65.0 AS build

RUN rustup override set nightly

RUN cargo new --bin /usr/local/src/builder

WORKDIR /usr/local/src/builder

COPY Cargo.toml Cargo.toml

RUN cargo build

RUN rm src/*.rs

COPY src/* src/

RUN cargo build --bin server

FROM debian:buster-slim AS run

EXPOSE 80

WORKDIR /app

COPY --from=build /usr/local/src/builder/target/debug/server .

COPY Rocket.toml .

ENTRYPOINT [ "/app/server" ]